### ISSUE TITLE
1.6	图形输出包  bug

### ISSUE THREAD

**Issue by sensen1** [adam18975257327/emc#1]
#### 1

图形输出，目前 X Y 轴 **`缺少`** 坐标轴的含义的定义，

比如 bokeh下面样式
[带X Y坐标轴说明的 官方例子 boxplot_chart](http://bokeh.pydata.org/en/latest/docs/gallery/boxplot_chart.html)
#### 2

目前的 图形定义，限定了必须 定义两条线，所以 sencond chart 如果不输入 ，不允许保存。 这个 应该是作为可选，不用必须。
#### 3

目前 图形下面的文字区域 输入的文字不会显示出来，怎么输入都不显示 

比如 系统里面的 下面位置
**`项目容器/笔记本E210/网卡/视图测试1`**
#### 4

 图左上角的 bokeh 图标和链接 不保留

**Comment by adam18975257327** [comment]
部分修复，boken tool bar 保留的好，可以导出图片。
