### ISSUE TITLE
1.5 标签管理包

### ISSUE THREAD

**Issue by sensen1** [adam18975257327/emc#2]
标签组的 设置，在 站点设置里面的， **`标签管理`** 那里，

目前我添加了 另外一个组，比如 

EDA-ADS
EDA-CST
EDA-FEKO
EDA-HFSS
EDA-Sonnet

目前标签组 不是希望的效果，另外 添加上述标签后，标签组显示效果已乱

比如   显卡 节点。

问题 1 
标签组  要根据 项目分组，不是都在一个组。 如下

EDA-ADS
EDA-CST
EDA-FEKO
EDA-HFSS
EDA-Sonnet
项目-标准
项目-规范
项目-设计

项目是一组标签， EDA是另一组标签。  标签过滤时，我可以选 每组标签里的任何标签。 

这个效果 在易度里面解释过。

比如 下面的链接 

[易度标签效果，右侧 tag部分为标签组 ](http://dms.easydo.cn/default/wdk/filerepos/%E7%A0%94%E5%8F%91%E6%96%87%E6%A1%A3/@@taggroup)

问题 2

今后多标签组定义后，界面显示安排的考虑，是否考虑 下拉或者扩展等方式，目前 全部显示的方式 跳过占地方，也不方便分类。

**Comment by adam18975257327** [comment]
解决
