### ISSUE TITLE
1.3 项目管理包

### ISSUE THREAD

**Issue by sensen1** [adam18975257327/emc#4]
1  项目树节点 默认视图 侧栏操作丢失

默认视图目前可能应该没有定义为标准视图，所以默认视图下，左侧 操作 都没法显示。 比如 编辑 等。

2  项目树 显示效果

项目树 的各个分支 应该只 显示 设备，设备下面的 内容不应该出现在 项目树 里面， 比如 网卡节点下面

视图测试1 
故障诊断  
网卡审核  
网卡设计  
网卡分析  
网卡

上面这些 正常是不该显示在 项目树里面的，而是显示在 页面中部的视图区。

3 项目树 子节点的层级效果

我在 网卡节点下面  又建立了一个 网卡芯片 节点，但是目前 这个节点 和 网卡节点 显示效果为并列， 并看不出层级，并且也没有在 网卡节点里面展开。

**Comment by adam18975257327** [comment]
已修复
